### ISSUE TITLE
Providing other fonts of Google Sans family

### ISSUE THREAD

**Issue by tuduongquyet** [surfaceflinger/google-sans-nix#1]
Please providing other fonts of Google Sans family:
https://fonts.googleapis.com/css2?family=Google+Sans:wght@400;500;700&display=swap
https://fonts.googleapis.com/css2?family=Google+Sans+Text:wght@400;500;700&display=swap
https://fonts.googleapis.com/css2?family=Google+Sans+Mono:wght@400;500;700&display=swap

**Comment by surfaceflinger** [comment]
i only want to package fonts from chromeos here
